channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
 - pytorch==1.13.1 
 - torchvision==0.14.1 
 - pandas
 - pydicom
 - matplotlib
 - pytorch-lightning
 - tensorboard
 #- torchaudio==0.13.1 
 #- pytorch-cuda=11.6